export const STEPS = {
  AWAIT_GROUP_PICK: "AWAIT_GROUP_PICK",
  AWAIT_GROUP_NAME_FOR_REQUEST: "AWAIT_GROUP_NAME_FOR_REQUEST",

  TASK_TITLE: "TASK_TITLE",
  TASK_DESC: "TASK_DESC",
  TASK_DUE: "TASK_DUE",
  TASK_SUBJECT_PICK: "TASK_SUBJECT_PICK",
  TASK_SCOPE: "TASK_SCOPE",

  SUBJECT_NAME: "SUBJECT_NAME",

  ROLE_MENU: "ROLE_MENU",
  ROLE_BY_ID_INPUT: "ROLE_BY_ID_INPUT",
  ROLE_PICK_GROUP_FROM_LIST: "ROLE_PICK_GROUP_FROM_LIST",
  ROLE_PICK_USER_FROM_GROUP: "ROLE_PICK_USER_FROM_GROUP",
  ROLE_PICK_TYPE: "ROLE_PICK_TYPE",
  ROLE_PICK_GROUP_FOR_CURATOR: "ROLE_PICK_GROUP_FOR_CURATOR",

  CURATOR_NOTIFY_TEXT: "CURATOR_NOTIFY_TEXT",

  SUBJECT_NAME: "SUBJECT_NAME",
  SUBJECT_DELETE_PICK: "SUBJECT_DELETE_PICK",
};
