export const STEPS = {
  AWAIT_GROUP_PICK: "AWAIT_GROUP_PICK",
  AWAIT_GROUP_NAME_FOR_REQUEST: "AWAIT_GROUP_NAME_FOR_REQUEST",

  TASK_TITLE: "TASK_TITLE",
  TASK_DESC: "TASK_DESC",
  TASK_DUE: "TASK_DUE",
  TASK_SUBJECT_PICK: "TASK_SUBJECT_PICK",
  TASK_SCOPE: "TASK_SCOPE",

  SUBJECT_NAME: "SUBJECT_NAME",
};
